#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# Values are captured into a root .env first, so a re-run can offer them back
# as defaults. The last stage fans them out to the three files the apps read.
ENV_FILE=".env"

banner "Auth0 + Supabase setup for insightt-crud"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Auth0 tenant"
say "You need an Auth0 tenant. Free is fine, and you are its owner, so every"
say "setting in this wizard is yours to change."
open_url "https://auth0.com/signup"
step "Sign up, or log in if you already have a tenant."
step "Pick any region. Note the tenant domain shown top-left in the dashboard,"
step "  e.g. dev-ab12cd34.us.auth0.com"
ask AUTH0_DOMAIN "Paste your Auth0 domain (no https://):"
write_env AUTH0_DOMAIN "$AUTH0_DOMAIN"
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Auth0 API (the audience)"
say "This registers the Express API as a protected resource. Its identifier"
say "becomes the 'audience' every access token is minted for."
warn "APIs and Applications are two DIFFERENT sections of the sidebar."
note "  This stage is the APIs one. Creating an *Application* named 'api'"
note "  instead is the commonest way to get stuck here: you end up with no"
note "  audience to paste except the tenant's own Management API, and every"
note "  later stage then fails in a way that does not point back to this one."
open_url "https://manage.auth0.com/dashboard"
step "Applications -> APIs -> + Create API     <- the APIs sub-item"
step "  Name:       insightt-crud API"
step "  Identifier: https://insightt-crud/api    (this is just a URN, not a URL"
step "              that has to resolve - but it can never be changed later)"
step "  Signing Algorithm: RS256"
step "Click Create."
say ""
say "Then, on the new API's Settings tab, scroll to Access Settings:"
step "  Toggle ON 'Allow Offline Access'."
note "  Without it Auth0 silently refuses to issue refresh tokens, and the SPA"
note "  is configured for rotating refresh tokens (PLAN.md 342)."
step "Click Save."
note "Auth0 also auto-creates a Machine to Machine app called"
note "  'insightt-crud API (Test Application)'. Nothing here uses it; ignore it."
ask AUTH0_AUDIENCE "Paste the API Identifier you used:"
while [[ "$AUTH0_AUDIENCE" == *"/api/v2/" || "$AUTH0_AUDIENCE" == "https://$AUTH0_DOMAIN/"* ]]; do
  warn "That is the tenant's own Management API, not the API you just created."
  note "  Go back to Applications -> APIs, open 'insightt-crud API', and copy"
  note "  the Identifier field from its Settings tab."
  ask AUTH0_AUDIENCE "Paste the API Identifier again:"
done
write_env AUTH0_AUDIENCE "$AUTH0_AUDIENCE"
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Auth0 SPA application (the browser client)"
say "This is the application the Next.js frontend logs in through."
open_url "https://manage.auth0.com/dashboard"
step "Applications -> Applications -> + Create Application"
step "  Name: insightt-crud web"
step "  Type: Single Page Web Applications      <- must be this type"
say ""
say "Open its Settings tab. Under Application URIs, set ALL THREE of these to"
say "http://localhost:3000"
step "  - Allowed Callback URLs"
step "  - Allowed Logout URLs"
step "  - Allowed Web Origins"
warn "Do NOT type anything into 'Application Login URI'."
note "  It sits directly above Allowed Callback URLs, it is optional, and it"
note "  must be https - so pasting localhost there fails with a validation"
note "  error on property initiate_login_uri. Leave it empty."
note "Leave 'Allowed Origins (CORS)' empty too: Auth0 already includes the"
note "  callback URLs in it, and the API's own CORS comes from WEB_ORIGIN."
note "Each field is a tag input - type the URL, then press Enter so it turns"
note "  into a chip, before moving to the next field."
say ""
step "Still on Settings, scroll to Refresh Token Rotation and toggle ON"
step "  'Allow Refresh Token Rotation'."
step "Scroll to the bottom and click Save Changes."
warn "Save Changes is easy to miss; the fields look saved before you click it."
ask AUTH0_SPA_CLIENT_ID "Paste this application's Client ID:"
write_env AUTH0_SPA_CLIENT_ID "$AUTH0_SPA_CLIENT_ID"
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Auth0 Cypress application (E2E only)"
say "Auth0 does NOT offer the Password grant on Single Page Application clients,"
say "so the Cypress test cannot reuse the app from the last stage. This second"
say "application exists only to mint tokens programmatically in tests."
open_url "https://manage.auth0.com/dashboard"
step "Applications -> Applications -> + Create Application"
step "  Name: insightt-crud cypress"
step "  Type: Regular Web Applications          <- must be this type"
step "Open Settings -> scroll to Advanced Settings -> Grant Types tab"
step "  Tick: Password        (leave the others as they are)"
step "Click Save Changes."
note "If the last stage reports 'not authorized to access resource server',"
note "  open this app's API Access tab and authorize 'insightt-crud API'."
ask AUTH0_CYPRESS_CLIENT_ID "Paste the Cypress app's Client ID:"
ask_secret AUTH0_CYPRESS_CLIENT_SECRET "Paste the Cypress app's Client Secret (hidden):"
write_env AUTH0_CYPRESS_CLIENT_ID "$AUTH0_CYPRESS_CLIENT_ID"
write_env AUTH0_CYPRESS_CLIENT_SECRET "$AUTH0_CYPRESS_CLIENT_SECRET"
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Connections: database on, social off"
say "A task's owner is its Auth0 'sub', and 'sub' is scoped to the connection."
say "If Google stays enabled, the same person logging in with Google and with"
say "email/password becomes two different owners with two disjoint task lists."
open_url "https://manage.auth0.com/dashboard"
step "Authentication -> Social"
step "  Toggle OFF every connection listed here. A brand-new tenant often has"
step "  none at all, in which case the page says 'No items have been added to"
step "  this section' and there is nothing to do - the Google and Apple buttons"
step "  drawn above that line are an illustration, not live connections."
step "Authentication -> Database -> Username-Password-Authentication"
step "  Applications tab: make sure BOTH insightt-crud apps are toggled ON."
step "  Settings tab: leave 'Disable Sign Ups' OFF, so a reviewer can register."
ask AUTH0_REALM "Database connection name [Username-Password-Authentication]:"
AUTH0_REALM="${AUTH0_REALM:-Username-Password-Authentication}"
write_env AUTH0_REALM "$AUTH0_REALM"
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Test user for Cypress"
say "One real user in the database connection. Cypress logs in as this user."
open_url "https://manage.auth0.com/dashboard"
step "User Management -> Users -> + Create User"
step "  Connection: $AUTH0_REALM"
step "  Email and password: anything you like, but the password must satisfy"
step "  the tenant policy (8+ chars, mixed case and a digit is always safe)."
ask AUTH0_TEST_EMAIL "Test user email:"
ask_secret AUTH0_TEST_PASSWORD "Test user password (hidden):"
write_env AUTH0_TEST_EMAIL "$AUTH0_TEST_EMAIL"
write_env AUTH0_TEST_PASSWORD "$AUTH0_TEST_PASSWORD"
pause "Press Enter to continue"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Supabase connection string"
say "The API talks to Supabase as plain Postgres over the Supavisor pooler in"
say "SESSION mode. Transaction mode does not support prepared statements, and"
say "the direct connection is IPv6-first."
open_url "https://supabase.com/dashboard/projects"
step "Open your project -> Connect (top bar)"
step "Choose 'Session pooler' and copy the URI. It looks like:"
step "  postgresql://postgres.<ref>:<password>@aws-0-<region>.pooler.supabase.com:5432/postgres"
warn "Not the 'Transaction pooler' (port 6543) and not the direct connection."
step "Replace [YOUR-PASSWORD] in the string with your database password."
ask_secret DATABASE_URL "Paste the session-mode connection string (hidden):"
write_env DATABASE_URL "$DATABASE_URL"
pause "Press Enter to continue"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Write env files and verify"
say "Fanning the captured values out to the files each app actually reads."

mkdir -p apps/api apps/web

cat > apps/api/.env <<APIENV
DATABASE_URL=$DATABASE_URL
AUTH0_DOMAIN=$AUTH0_DOMAIN
AUTH0_AUDIENCE=$AUTH0_AUDIENCE
PORT=4000
WEB_ORIGIN=http://localhost:3000
APIENV
printf '  %s✓ wrote%s apps/api/.env\n' "$GREEN" "$RESET"

cat > apps/web/.env.local <<WEBENV
NEXT_PUBLIC_AUTH0_DOMAIN=$AUTH0_DOMAIN
NEXT_PUBLIC_AUTH0_CLIENT_ID=$AUTH0_SPA_CLIENT_ID
NEXT_PUBLIC_AUTH0_AUDIENCE=$AUTH0_AUDIENCE
NEXT_PUBLIC_API_URL=http://localhost:4000
WEBENV
printf '  %s✓ wrote%s apps/web/.env.local\n' "$GREEN" "$RESET"

# Both client ids, and each is named for its client: Cypress mints the token
# with the Regular Web App, then stores it under the SPA client's cache key,
# which is the only key the browser app looks under.
#
# These key names changed when the E2E spec landed. A cypress.env.json written
# by an older run of this script has no AUTH0_SPA_CLIENT_ID and spells the other
# two AUTH0_CLIENT_ID / AUTH0_CLIENT_SECRET; it is overwritten below, and a
# hand-edited one fails the spec by naming the key it is missing.
cat > cypress.env.json <<CYENV
{
  "AUTH0_DOMAIN": "$AUTH0_DOMAIN",
  "AUTH0_AUDIENCE": "$AUTH0_AUDIENCE",
  "AUTH0_REALM": "$AUTH0_REALM",
  "AUTH0_SPA_CLIENT_ID": "$AUTH0_SPA_CLIENT_ID",
  "AUTH0_CYPRESS_CLIENT_ID": "$AUTH0_CYPRESS_CLIENT_ID",
  "AUTH0_CYPRESS_CLIENT_SECRET": "$AUTH0_CYPRESS_CLIENT_SECRET",
  "AUTH0_TEST_EMAIL": "$AUTH0_TEST_EMAIL",
  "AUTH0_TEST_PASSWORD": "$AUTH0_TEST_PASSWORD"
}
CYENV
printf '  %s✓ wrote%s cypress.env.json\n' "$GREEN" "$RESET"

for pattern in ".env" "apps/api/.env" "apps/web/.env.local" "cypress.env.json"; do
  if ! grep -qxF "$pattern" .gitignore 2>/dev/null; then
    printf '%s\n' "$pattern" >> .gitignore
    note "added $pattern to .gitignore"
  fi
done

if ! command -v curl >/dev/null 2>&1; then
  SKIPPED+=("all verification (curl not found)")
  warn "curl not found; skipping verification"
  pause "Press Enter to finish"
  finish
  exit 0
fi

# Two independent checks, because they fail for unrelated reasons. The token
# mint exercises the API, the realm, the test user and the Cypress app; the
# /authorize probe exercises the SPA app, which nothing else here touches.
# Without the second, a deleted SPA or an empty callback list stays invisible
# until the first real login attempt.

say ""
say "Verifying the Cypress credentials can actually mint a token..."
# The same grant, realm and scope the E2E spec sends; keep this and
# cypress/support/auth0.ts in step, or a tenant that passes setup still fails
# the spec with an error that names neither file.
RESPONSE=$(curl -s -X POST "https://$AUTH0_DOMAIN/oauth/token" \
  -H "Content-Type: application/json" \
  -d "{\"grant_type\":\"http://auth0.com/oauth/grant-type/password-realm\",\"realm\":\"$AUTH0_REALM\",\"username\":\"$AUTH0_TEST_EMAIL\",\"password\":\"$AUTH0_TEST_PASSWORD\",\"audience\":\"$AUTH0_AUDIENCE\",\"scope\":\"openid profile email offline_access\",\"client_id\":\"$AUTH0_CYPRESS_CLIENT_ID\",\"client_secret\":\"$AUTH0_CYPRESS_CLIENT_SECRET\"}" 2>/dev/null || true)
if printf '%s' "$RESPONSE" | grep -q '"access_token"'; then
  printf '  %s✓ token minted successfully - Cypress login will work%s\n' "$GREEN" "$RESET"
  if printf '%s' "$RESPONSE" | grep -q '"refresh_token"'; then
    printf '  %s✓ refresh token issued - Allow Offline Access is on%s\n' "$GREEN" "$RESET"
  else
    warn "no refresh token came back"
    note "  Stage 2: turn ON 'Allow Offline Access' on the API. The SPA needs it."
    SKIPPED+=("API Allow Offline Access is off")
  fi
else
  warn "could not mint a token. Auth0 said:"
  note "  $RESPONSE"
  note "  'Grant type not allowed'   -> stage 4: enable the Password grant"
  note "  'not authorized to access resource server'"
  note "                             -> stage 4: API Access tab, authorize the API"
  note "  'Service not found'        -> stage 2: the audience is not a real API"
  note "  'Unknown or invalid realm' -> stage 5: check the connection name"
  note "  'Wrong email or password'  -> stage 6: recheck the test user"
  SKIPPED+=("Cypress token mint failed - re-run after fixing the above")
fi

say ""
say "Verifying the SPA client id and its callback URL..."
# /authorize separates the two SPA failure modes by status code alone:
#   302 -> client exists and http://localhost:3000 is a registered callback
#   403 -> client exists, callback URL not registered
#   400 -> Auth0 has never heard of this client id
SPA_CODE=$(curl -s -o /dev/null -w '%{http_code}' \
  "https://$AUTH0_DOMAIN/authorize?client_id=$AUTH0_SPA_CLIENT_ID&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3000&scope=openid" 2>/dev/null || true)
case "$SPA_CODE" in
  302)
    printf '  %s✓ SPA client and callback URL both accepted%s\n' "$GREEN" "$RESET" ;;
  403)
    warn "Auth0 knows this client but rejects the callback URL."
    note "  Stage 3: add http://localhost:3000 to Allowed Callback URLs and Save."
    SKIPPED+=("SPA Allowed Callback URLs are not set") ;;
  400)
    warn "Auth0 does not recognise client id $AUTH0_SPA_CLIENT_ID."
    note "  Stage 3: it was deleted, or a different app Client ID was pasted."
    SKIPPED+=("SPA client id does not exist") ;;
  *)
    warn "unexpected HTTP $SPA_CODE from /authorize; verify stage 3 by hand"
    SKIPPED+=("SPA verification inconclusive (HTTP $SPA_CODE)") ;;
esac

pause "Press Enter to finish"

finish
